const ingredientsList = [
  "Abaia Serpe",
  "Albenaja",
  "Apple",
  "Aquanaja",
  "Aquatic Snail",
  "Barley",
  "Basil",
  "Bass",
  "Berry",
  "Blue-blooded Barb",
  "Blue-Winged Serpe",
  "Blueberry",
  "Bluefish",
  "Bread",
  "Broccoli",
  "Butter",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Cheese",
  "Cinnamon",
  "Coconut",
  "Cooking Oil",
  "Corn",
  "Cranberry",
  "Daemonaja",
  "Delicate Fish Filet",
  "Dill",
  "Egede Serpe",
  "Egg",
  "Firm Fish Filet",
  "Fish Filet",
  "Fish Filet",
  "Fish Oil",
  "Fish Roe",
  "Flounder",
  "Flour",
  "Game Meat",
  "Garlic",
  "Ginger",
  "Glowing Gnufish",
  "Glowing Guardfish",
  "Hake",
  "Honey",
  "Horned-Tooth Mandje",
  "Juicy Ham Hock",
  "Large Bass",
  "Large Bluefish",
  "Large Catfish",
  "Large Cod",
  "Large Dragon Fish",
  "Large Electric Eel",
  "Large Flounder",
  "Large Frogfish",
  "Large Hake",
  "Large Halibut",
  "Large Mackerel",
  "Large Madtom",
  "Large Paddlefish",
  "Large Perch",
  "Large Pike",
  "Large Piranha",
  "Large Salmon",
  "Large Sculpin",
  "Large Snapper",
  "Large Speartooth Shark",
  "Large Squid",
  "Large Stingray",
  "Large Sturgeon",
  "Large Sunfish",
  "Large Swordfish",
  "Large Trout",
  "Lava Barb",
  "Lemon",
  "Mackerel",
  "Mandje Mandje",
  "Medium Bass",
  "Medium Bluefish",
  "Medium Catfish",
  "Medium Cod",
  "Medium Dragon Fish",
  "Medium Electric Eel",
  "Medium Flounder",
  "Medium Frogfish",
  "Medium Hake",
  "Medium Halibut",
  "Medium Mackerel",
  "Medium Madtom",
  "Medium Paddlefish",
  "Medium Perch",
  "Medium Pike",
  "Medium Piranha",
  "Medium Salmon",
  "Medium Sculpin",
  "Medium Snapper",
  "Medium Speartooth Shark",
  "Medium Squid",
  "Medium Stingray",
  "Medium Sturgeon",
  "Medium Sunfish",
  "Medium Swordfish",
  "Medium Trout",
  "Melon",
  "Milk",
  "Mint",
  "Mushroom",
  "Nut",
  "Nutmeg",
  "Oil",
  "Onion",
  "Orange",
  "Oregano",
  "Oyster",
  "Paprika",
  "Parsley",
  "Pasta",
  "Pastry Crust",
  "Peppercorn",
  "Pork",
  "Pork Belly",
  "Potato",
  "Poultry",
  "Poultry Breast",
  "Poultry Thigh",
  "Prime Red Meat",
  "Ray-Finned Barb",
  "Red Meat",
  "Rice",
  "Rich Bear Flank",
  "Rosemary",
  "Saffron",
  "Sage",
  "Salt",
  "Sausage",
  "Seasoning Blend",
  "Small Bass",
  "Small Bluefish",
  "Small Catfish",
  "Small Cod",
  "Small Dragon Fish",
  "Small Electric Eel",
  "Small Flounder",
  "Small Frogfish",
  "Small Hake",
  "Small Halibut",
  "Small Mackerel",
  "Small Madtom",
  "Small Paddlefish",
  "Small Perch",
  "Small Pike",
  "Small Piranha",
  "Small Salmon",
  "Small Sculpin",
  "Small Snapper",
  "Small Speartooth Shark",
  "Small Squid",
  "Small Stingray",
  "Small Sturgeon",
  "Small Sunfish",
  "Small Swordfish",
  "Small Trout",
  "Squash",
  "Squid Ink",
  "Squid Meat",
  "Strawberry",
  "String Bean",
  "Sugar",
  "Sumptuous Rabbit",
  "Tadpole",
  "Tarragon",
  "Tender Fish Filet",
  "Tender Wolf Loin",
  "Thyme",
  "Tomato",
  "Varanus Mandje",
  "Venison",
  "Venison Tenderloin",
  "Water",
  "Wheat",
  "Yeast",
];

export default ingredientsList;