export const mealsData = {
  meatpie: {
    tier: "Tier 2",
    stat: "10 Dexterity",
    lvl: "Lv. 27",
    meal: "Meat Pie",
    in1: "Game Meat",
    in2: "Pastry Crust",
    in3: "Rosemary",
    in4: "Peppercorn",
    in5: "",
    in6: "",
    in7: "",
  },
  shootersandwich: {
    tier: "Tier 2",
    stat: "6 Dexterity and 4 Strength",
    lvl: "Lv. 26",
    meal: "Shooter Sandwich",
    in1: "Bread",
    in2: "Red Meat",
    in3: "Onion",
    in4: "Cheese",
    in5: "",
    in6: "",
    in7: "",
  },
  roastporkshank: {
    tier: "Tier 2",
    stat: "6 Dexterity and 4 Intelligence",
    lvl: "Lv. 28",
    meal: "Roast Pork Shank",
    in1: "Pork",
    in2: "Cabbage",
    in3: "Butter",
    in4: "Sage",
    in5: "",
    in6: "",
    in7: "",
  },
  poachedfishwithlemonanddill: {
    tier: "Tier 2",
    stat: "6 Dexterity and 4 Constitution",
    lvl: "Lv. 29",
    meal: "Poached Fish With Lemon and Dill",
    in1: "Fish Filet",
    in2: "Water",
    in3: "Lemon",
    in4: "Dill",
    in5: "",
    in6: "",
    in7: "",
  },
  applepie: {
    tier: "Tier 2",
    stat: "6 Dexterity and 4 Focus",
    lvl: "Lv. 30",
    meal: "Apple Pie",
    in1: "Pastry Crust",
    in2: "Apple",
    in3: "Sugar",
    in4: "Cinnamon",
    in5: "",
    in6: "",
    in7: "",
  },
  honeyedmelon: {
    tier: "Tier 3",
    stat: "20 Dexterity",
    lvl: "Lv. 77",
    meal: "Honeyed Melon",
    in1: "Melon",
    in2: "Honey",
    in3: "Sugar",
    in4: "Mint",
    in5: "Ginger",
    in6: "",
    in7: "",
  },
  citrustart: {
    tier: "Tier 3",
    stat: "12 Dexterity and 8 Strength",
    lvl: "Lv.",
    meal: "Citrus Tart",
    in1: "Pastry Crust",
    in2: "Egg",
    in3: "Lemon",
    in4: "Orange",
    in5: "Sugar",
    in6: "",
    in7: "",
  },
  coconutcustard: {
    tier: "Tier 3",
    stat: "12 Dexterity and 8 Intelligence",
    lvl: "Lv.",
    meal: "Coconut Custard",
    in1: "Coconut",
    in2: "Egg",
    in3: "Sugar",
    in4: "Salt",
    in5: "Strawberry",
    in6: "",
    in7: "",
  },
  roastedgamebirdwithberryglaze: {
    tier: "Tier 3",
    stat: "12 Dexterity and 8 Constitution",
    lvl: "Lv.",
    meal: "Roasted Game Bird with Berry Glaze",
    in1: "Poultry",
    in2: "Mint",
    in3: "Sugar",
    in4: "Berry",
    in5: "Peppercorn",
    in6: "",
    in7: "",
  },
  cheesecake: {
    tier: "Tier 3",
    stat: "12 Dexterity and 8 Focus",
    lvl: "Lv.",
    meal: "Cheesecake",
    in1: "Cheese",
    in2: "Pastry Crust",
    in3: "Milk",
    in4: "Sugar",
    in5: "Strawberry",
    in6: "",
    in7: "",
  },
  seafoodbisque: {
    tier: "Tier 4",
    stat: "30 Dexterity",
    lvl: "Lv. 127",
    meal: "Seafood Bisque",
    in1: "Oyster Bait",
    in2: "Milk",
    in3: "Salt",
    in4: "Garlic",
    in5: "Rosemary",
    in6: "Paprika",
    in7: "",
  },
  frenchtoast: {
    tier: "Tier 4",
    stat: "18 Dexterity and 12 Strength",
    lvl: "Lv. 126",
    meal: "French Toast",
    in1: "Bread",
    in2: "Egg",
    in3: "Milk",
    in4: "Cinnamon",
    in5: "Honey",
    in6: "Butter",
    in7: "",
  },
  roastedwolfloin: {
    tier: "Tier 4",
    stat: "18 Dexterity and 12 Intelligence",
    lvl: "Lv. 128",
    meal: "Roasted Wolf Loin",
    in1: "Tender Wolf Loin",
    in2: "String Bean",
    in3: "Broccoli",
    in4: "Carrot",
    in5: "Mushroom",
    in6: "Thyme",
    in7: "",
  },
  filetwithmintandcrackedbarley: {
    tier: "Tier 4",
    stat: "18 Dexterity and 12 Constitution",
    lvl: "Lv. 129",
    meal: "Filet with Mint and Cracked Barley",
    in1: "Prime Red Meat",
    in2: "Barley",
    in3: "Water",
    in4: "Mint",
    in5: "Salt",
    in6: "Peppercorn",
    in7: "",
  },
  paella: {
    tier: "Tier 4",
    stat: "18 Dexterity and 12 Focus",
    lvl: "Lv. 130",
    meal: "Paella",
    in1: "Rice",
    in2: "Saffron",
    in3: "Oyster Bait",
    in4: "Poultry",
    in5: "Garlic",
    in6: "Onion",
    in7: "",
  },
  friedalbenaja: {
    tier: "Tier 5",
    stat: "40 Dexterity",
    lvl: "Lv. 177",
    meal: "Fried Albenaja",
    in1: "Albenaja",
    in2: "Cooking Oil",
    in3: "Seasoning Blend",
    in4: "Cabbage",
    in5: "Cauliflower",
    in6: "Flour",
    in7: "Egg",
  },
  fallharvestturkey: {
    tier: "Tier 5",
    stat: "24 Dexterity and 16 Strength",
    lvl: "Lv. 176",
    meal: "Fall Harvest Turkey",
    in1: "Poultry Thigh",
    in2: "Cranberry",
    in3: "Potato",
    in4: "Carrot",
    in5: "Parsley",
    in6: "Sage",
    in7: "Thyme",
  },
  "poacher'spie": {
    tier: "Tier 5",
    stat: "24 Dexterity and 16 Intelligence",
    lvl: "Lv. 178",
    meal: "Poacher's Pie",
    in1: "Sumptuous Rabbit",
    in2: "Carrot",
    in3: "Onion",
    in4: "Egg",
    in5: "Flour",
    in6: "Cooking Oil",
    in7: "Seasoning Blend",
  },
  rabbitstew: {
    tier: "Tier 5",
    stat: "24 Dexterity and 16 Constitution",
    lvl: "Lv. 179",
    meal: "Rabbit Stew",
    in1: "Sumptuous Rabbit",
    in2: "Carrot",
    in3: "Potato",
    in4: "Onion",
    in5: "Thyme",
    in6: "Rosemary",
    in7: "Sage",
  },
  carbonara: {
    tier: "Tier 5",
    stat: "24 Dexterity and 16 Focus",
    lvl: "Lv. 180",
    meal: "Carbonara",
    in1: "Pasta",
    in2: "Pork Belly",
    in3: "Salt",
    in4: "Cheese",
    in5: "Egg",
    in6: "Peppercorn",
    in7: "Cooking Oil",
  },
  porkchopsandapplesauce: {
    tier: "Tier 2",
    stat: "10 Strength",
    lvl: "Lv. 21",
    meal: "Pork Chops and Apple Sauce",
    in1: "Pork",
    in2: "Cooking Oil",
    in3: "Cinnamon",
    in4: "Apple",
    in5: "",
    in6: "",
    in7: "",
  },
  garlicsteak: {
    tier: "Tier 2",
    stat: "6 Strength and 4 Dexterity",
    lvl: "Lv. 22",
    meal: "Garlic Steak",
    in1: "Red Meat",
    in2: "Butter",
    in3: "Garlic",
    in4: "Broccoli",
    in5: "",
    in6: "",
    in7: "",
  },
  roastedcarrotswithdill: {
    tier: "Tier 2",
    stat: "6 Strength and 4 Intelligence",
    lvl: "Lv. 23",
    meal: "Roasted Carrots With Dill",
    in1: "Carrot",
    in2: "Butter",
    in3: "Dill",
    in4: "Salt",
    in5: "",
    in6: "",
    in7: "",
  },
  cheesybroccolisoup: {
    tier: "Tier 2",
    stat: "6 Strength and 4 Constitution",
    lvl: "Lv. 24",
    meal: "Cheesy Broccoli Soup",
    in1: "Broccoli",
    in2: "Cheese",
    in3: "Salt",
    in4: "Milk",
    in5: "",
    in6: "",
    in7: "",
  },
  fruitsalad: {
    tier: "Tier 2",
    stat: "6 Strength and 4 Focus",
    lvl: "Lv. 25",
    meal: "Fruit Salad",
    in1: "Apple",
    in2: "Blueberry",
    in3: "Strawberry",
    in4: "Orange",
    in5: "",
    in6: "",
    in7: "",
  },
  supremeomelet: {
    tier: "Tier 3",
    stat: "20 Strength",
    lvl: "Lv. 71",
    meal: "Supreme Omelet",
    in1: "Sausage",
    in2: "Tomato",
    in3: "Onion",
    in4: "Mushroom",
    in5: "Cheese",
    in6: "",
    in7: "",
  },
  friedcalamari: {
    tier: "Tier 3",
    stat: "12 Strength and 8 Dexterity",
    lvl: "Lv.",
    meal: "Fried Calamari",
    in1: "Squid Meat",
    in2: "Flour",
    in3: "Lemon",
    in4: "Cooking Oil",
    in5: "Egg",
    in6: "",
    in7: "",
  },
  stuffedsquash: {
    tier: "Tier 3",
    stat: "12 Strength and 8 Intelligence",
    lvl: "Lv.",
    meal: "Stuffed Squash",
    in1: "Squash",
    in2: "Red Meat",
    in3: "Cheese",
    in4: "Mushroom",
    in5: "Parsley",
    in6: "",
    in7: "",
  },
  steakwithmushroomgravy: {
    tier: "Tier 3",
    stat: "12 Strength and 8 Constitution",
    lvl: "Lv.",
    meal: "Steak with Mushroom Gravy",
    in1: "Red Meat",
    in2: "Mushroom",
    in3: "Flour",
    in4: "Peppercorn",
    in5: "Salt",
    in6: "",
    in7: "",
  },
  blueberrypie: {
    tier: "Tier 3",
    stat: "12 Strength and 8 Focus",
    lvl: "Lv. 75",
    meal: "Blueberry Pie",
    in1: "Pastry Crust",
    in2: "Blueberry",
    in3: "Sugar",
    in4: "Butter",
    in5: "Honey",
    in6: "",
    in7: "",
  },
  clamchowder: {
    tier: "Tier 4",
    stat: "30 Strength",
    lvl: "Lv. 121",
    meal: "Clam Chowder",
    in1: "Clam",
    in2: "Potato",
    in3: "Onion",
    in4: "Milk",
    in5: "Flour",
    in6: "Garlic",
    in7: "",
  },
  venisonroast: {
    tier: "Tier 4",
    stat: "18 Strength and 12 Dexterity",
    lvl: "Lv. 122",
    meal: "Venison Roast",
    in1: "Venison",
    in2: "Squash",
    in3: "Potato",
    in4: "Mushroom",
    in5: "Sage",
    in6: "Onion",
    in7: "",
  },
  pestostuffedturkeybreast: {
    tier: "Tier 4",
    stat: "18 Strength and 12 Intelligence",
    lvl: "Lv. 123",
    meal: "Pesto-Stuffed Turkey Breast",
    in1: "Poultry Breast",
    in2: "Basil",
    in3: "Cooking Oil",
    in4: "Nut",
    in5: "Cheese",
    in6: "Garlic",
    in7: "",
  },
  bearflankpinwheels: {
    tier: "Tier 4",
    stat: "18 Strength and 12 Constitution",
    lvl: "Lv. 124",
    meal: "Bear Flank Pinwheels",
    in1: "Rich Bear Flank",
    in2: "Basil",
    in3: "Cheese",
    in4: "Mushroom",
    in5: "Garlic",
    in6: "Salt",
    in7: "",
  },
  fishandchips: {
    tier: "Tier 4",
    stat: "18 Strength and 12 focus",
    lvl: "Lv. 125",
    meal: "Fish and Chips",
    in1: "Fish Filet",
    in2: "Flour",
    in3: "Egg",
    in4: "Cooking Oil",
    in5: "Potato",
    in6: "Salt",
    in7: "",
  },
  roastedgnufish: {
    tier: "Tier 5",
    stat: "40 Strength",
    lvl: "Lv. 171",
    meal: "Roasted Gnufish",
    in1: "Glowing Gnufish",
    in2: "Onion",
    in3: "Barley",
    in4: "Garlic",
    in5: "Salt",
    in6: "Carrot",
    in7: "Rosemary",
  },
  baconwrappedscallops: {
    tier: "Tier 5",
    stat: "24 Strength and 16 Dexterity",
    lvl: "Lv. 172",
    meal: "Bacon-Wrapped Scallops",
    in1: "Clam",
    in2: "Pork Belly",
    in3: "Salt",
    in4: "Butter",
    in5: "Peppercorn",
    in6: "Lemon",
    in7: "Garlic",
  },
  spaghettibolognese: {
    tier: "Tier 5",
    stat: "24 Strength and 16 Intelligence",
    lvl: "Lv. 173",
    meal: "Spaghetti Bolognese",
    in1: "Pasta",
    in2: "Red Meat",
    in3: "Tomato",
    in4: "Onion",
    in5: "Carrot",
    in6: "Garlic",
    in7: "Oregano",
  },
  carrotcake: {
    tier: "Tier 5",
    stat: "24 Strength and 16 Constitution",
    lvl: "Lv. 174",
    meal: "Carrot Cake",
    in1: "Carrot",
    in2: "Flour",
    in3: "Egg",
    in4: "Butter",
    in5: "Sugar",
    in6: "Cinnamon",
    in7: "Nutmeg",
  },
  honeyroastedham: {
    tier: "Tier 5",
    stat: "24 Strength and 16 Focus",
    lvl: "Lv. 175",
    meal: "Honey Roasted Ham",
    in1: "Juicy Ham Hock",
    in2: "Butter",
    in3: "Honey",
    in4: "Cinnamon",
    in5: "Sugar",
    in6: "Salt",
    in7: "Orange",
  },
  venisonpotroast: {
    tier: "Tier 2",
    stat: "10 Focus",
    lvl: "Lv. 45",
    meal: "Venison Pot Roast",
    in1: "Venison",
    in2: "Onion",
    in3: "Garlic",
    in4: "Thyme",
    in5: "",
    in6: "",
    in7: "",
  },
  venisonjerky: {
    tier: "Tier 2",
    stat: "6 Focus and 4 Strength",
    lvl: "Lv. 41",
    meal: "Venison Jerky",
    in1: "Venison",
    in2: "Salt",
    in3: "Garlic",
    in4: "Ginger",
    in5: "",
    in6: "",
    in7: "",
  },
  fishwithtarragonandoregano: {
    tier: "Tier 2",
    stat: "6 Focus and 4 Dexterity",
    lvl: "Lv. 42",
    meal: "Fish with Tarragon and Oregano",
    in1: "Fish Filet",
    in2: "Cooking Oil",
    in3: "Tarragon",
    in4: "Oregano",
    in5: "",
    in6: "",
    in7: "",
  },
  meloncrèmetart: {
    tier: "Tier 2",
    stat: "6 Focus and 4 Intelligence",
    lvl: "Lv. 43",
    meal: "Melon Crème Tart",
    in1: "Melon",
    in2: "Milk",
    in3: "Pastry Crust",
    in4: "Sugar",
    in5: "",
    in6: "",
    in7: "",
  },
  gamemeatskewers: {
    tier: "Tier 2",
    stat: "6 Focus and 4 Constitution",
    lvl: "Lv. 44",
    meal: "Game Meat Skewers",
    in1: "Game Meat",
    in2: "Cooking Oil",
    in3: "Peppercorn",
    in4: "Oregano",
    in5: "",
    in6: "",
    in7: "",
  },
  bakedfishfilet: {
    tier: "Tier 3",
    stat: "20 Focus",
    lvl: "Lv. 95",
    meal: "Baked Fish Filet",
    in1: "Fish Filet",
    in2: "Butter",
    in3: "Dill",
    in4: "Lemon",
    in5: "Salt",
    in6: "",
    in7: "",
  },
  grilledporkwithspicedsquash: {
    tier: "Tier 3",
    stat: "12 Focus and 8 Strength",
    lvl: "Lv. 91",
    meal: "Grilled Pork with Spiced Squash",
    in1: "Pork",
    in2: "Seasoning Blend",
    in3: "Squash",
    in4: "Cinnamon",
    in5: "Sugar",
    in6: "",
    in7: "",
  },
  deepfriedpoultry: {
    tier: "Tier 3",
    stat: "12 Focus and 8 Dexterity",
    lvl: "Lv.",
    meal: "Deep Fried Poultry",
    in1: "Poultry",
    in2: "Cooking Oil",
    in3: "Seasoning Blend",
    in4: "Flour",
    in5: "Egg",
    in6: "",
    in7: "",
  },
  fruitsaladwithtoastedcoconut: {
    tier: "Tier 3",
    stat: "12 Focus and 8 Intelligence",
    lvl: "Lv.",
    meal: "Fruit Salad with Toasted Coconut",
    in1: "Orange",
    in2: "Strawberry",
    in3: "Berry",
    in4: "Coconut",
    in5: "Melon",
    in6: "",
    in7: "",
  },
  onionsmotheredpork: {
    tier: "Tier 3",
    stat: "12 Focus and 8 Constitution",
    lvl: "Lv. 94",
    meal: "Onion Smothered Pork",
    in1: "Pork",
    in2: "Onion",
    in3: "Cooking Oil",
    in4: "Mushroom",
    in5: "Thyme",
    in6: "",
    in7: "",
  },
  turkeypotpie: {
    tier: "Tier 4",
    stat: "30 Focus",
    lvl: "Lv. 145",
    meal: "Turkey Pot Pie",
    in1: "Poultry Breast",
    in2: "Pastry Crust",
    in3: "Carrot",
    in4: "Potato",
    in5: "Broccoli",
    in6: "Milk",
    in7: "",
  },
  caviarcrostini: {
    tier: "Tier 4",
    stat: "18 Focus and 12 Strength",
    lvl: "Lv. 141",
    meal: "Caviar Crostini",
    in1: "Fish Roe",
    in2: "Bread",
    in3: "Cheese",
    in4: "Large Salmon",
    in5: "Dill",
    in6: "Cooking Oil",
    in7: "",
  },
  berryglazedroastedham: {
    tier: "Tier 4",
    stat: "18 Focus and 12 Dexterity",
    lvl: "Lv. 142",
    meal: "Berry Glazed Roasted Ham",
    in1: "Juicy Ham Hock",
    in2: "Berry",
    in3: "Cranberry",
    in4: "Blueberry",
    in5: "Honey",
    in6: "Butter",
    in7: "",
  },
  cordonbleu: {
    tier: "Tier 4",
    stat: "18 Focus and 12 Intelligence",
    lvl: "Lv. 143",
    meal: "Cordon Bleu",
    in1: "Poultry",
    in2: "Juicy Ham Hock",
    in3: "Cheese",
    in4: "Butter",
    in5: "Rosemary",
    in6: "Thyme",
    in7: "",
  },
  orangethymeturkeybreast: {
    tier: "Tier 4",
    stat: "18 Focus and 12 Constitution",
    lvl: "Lv. 144",
    meal: "Orange Thyme Turkey Breast",
    in1: "Poultry Breast",
    in2: "Orange",
    in3: "Thyme",
    in4: "Cooking Oil",
    in5: "Garlic",
    in6: "Onion",
    in7: "",
  },
  blackenedmandjemandjewithcornsuccotash: {
    tier: "Tier 5",
    stat: "Clam",
    lvl: "Lv. 195",
    meal: "Blackened Mandje Mandje with Corn Succotash",
    in1: "Lava Barb",
    in2: "Seasoning Blend",
    in3: "Onion",
    in4: "Corn",
    in5: "Tomato",
    in6: "String Bean",
    in7: "Butter",
  },
  butterpoachedoystersonangelhair: {
    tier: "Tier 5",
    stat: "24 Focus and 16 Strength",
    lvl: "Lv. 191",
    meal: "Butter Poached Oysters on Angel Hair",
    in1: "Oyster Bait",
    in2: "Butter",
    in3: "Pasta",
    in4: "Cheese",
    in5: "Garlic",
    in6: "Mushroom",
    in7: "Parsley",
  },
  roastedturkeythigh: {
    tier: "Tier 5",
    stat: "24 Focus and 16 Dexterity",
    lvl: "Lv. 192",
    meal: "Roasted Turkey Thigh",
    in1: "Poultry Thigh",
    in2: "Salt",
    in3: "Rosemary",
    in4: "Parsley",
    in5: "Thyme",
    in6: "Sage",
    in7: "Peppercorn",
  },
  venisontenderloinwithblueberryglaze: {
    tier: "Tier 5",
    stat: "24 Focus and 16 Intelligence",
    lvl: "Lv. 193",
    meal: "Venison Tenderloin with Blueberry Glaze",
    in1: "Venison Tenderloin",
    in2: "Blueberry",
    in3: "Honey",
    in4: "Orange",
    in5: "Potato",
    in6: "Salt",
    in7: "Peppercorn",
  },
  slowroastedbearflankwithrootvegetables: {
    tier: "Tier 5",
    stat: "24 Focus and 16 Constitution",
    lvl: "Lv. 194",
    meal: "Slow Roasted Bear Flank with Root Vegetables",
    in1: "Rich Bear Flank",
    in2: "Garlic",
    in3: "Thyme",
    in4: "Tomato",
    in5: "Seasoning Blend",
    in6: "Carrot",
    in7: "Potato",
  },
  tarragonpoultrysliders: {
    tier: "Tier 2",
    stat: "10 Constitution",
    lvl: "Lv. 39",
    meal: "Tarragon Poultry Sliders",
    in1: "Poultry",
    in2: "Bread",
    in3: "Tarragon",
    in4: "Tomato",
    in5: "",
    in6: "",
    in7: "",
  },
  searedvenisonsteak: {
    tier: "Tier 2",
    stat: "6 Constitution and 4 Strength",
    lvl: "Lv. 36",
    meal: "Seared Venison Steak",
    in1: "Venison",
    in2: "Salt",
    in3: "Peppercorn",
    in4: "Butter",
    in5: "",
    in6: "",
    in7: "",
  },
  spicedmelonpie: {
    tier: "Tier 2",
    stat: "6 Constitution and 4 Dexterity",
    lvl: "Lv. 37",
    meal: "Spiced Melon Pie",
    in1: "Pastry Crust",
    in2: "Melon",
    in3: "Ginger",
    in4: "Cinnamon",
    in5: "",
    in6: "",
    in7: "",
  },
  butterpoachedgame: {
    tier: "Tier 2",
    stat: "6 Constitution and 4 Intelligence",
    lvl: "Lv. 38",
    meal: "Butter Poached Game",
    in1: "Game Meat",
    in2: "Butter",
    in3: "Basil",
    in4: "Garlic",
    in5: "",
    in6: "",
    in7: "",
  },
  gamestuffedappleswithmushrooms: {
    tier: "Tier 2",
    stat: "6 Constitution and 4 Focus",
    lvl: "Lv. 40",
    meal: "Game Stuffed Apples with Mushrooms",
    in1: "Game Meat",
    in2: "Apple",
    in3: "Mushroom",
    in4: "Nutmeg",
    in5: "",
    in6: "",
    in7: "",
  },
  gamemeatwithcitrusglaze: {
    tier: "Tier 3",
    stat: "20 Constitution",
    lvl: "Lv.",
    meal: "Game Meat with Citrus Glaze",
    in1: "Game Meat",
    in2: "Lemon",
    in3: "Orange",
    in4: "Honey",
    in5: "Peppercorn",
    in6: "",
    in7: "",
  },
  coconutcrustedfishfilet: {
    tier: "Tier 3",
    stat: "12 Constitution and 8 Strength",
    lvl: "Lv. 86",
    meal: "Coconut Crusted Fish Filet",
    in1: "Fish Filet",
    in2: "Coconut",
    in3: "Cooking Oil",
    in4: "Rice",
    in5: "Saffron",
    in6: "",
    in7: "",
  },
  ravioliwithbrownbutterandsage: {
    tier: "Tier 3",
    stat: "12 Constitution and 8 Dexterity",
    lvl: "Lv.",
    meal: "Ravioli with Brown Butter and Sage",
    in1: "Pasta",
    in2: "Butter",
    in3: "Cheese",
    in4: "Mushroom",
    in5: "Sage",
    in6: "",
    in7: "",
  },
  porkchopswithpangravy: {
    tier: "Tier 3",
    stat: "12 Constitution and 8 Intelligence",
    lvl: "Lv.",
    meal: "Pork Chops with Pan Gravy",
    in1: "Pork",
    in2: "Butter",
    in3: "Flour",
    in4: "Rosemary",
    in5: "Thyme",
    in6: "",
    in7: "",
  },
  grilledpoultrywithsaffronrice: {
    tier: "Tier 3",
    stat: "12 Constitution and 8 Focus",
    lvl: "Lv.",
    meal: "Grilled Poultry with Saffron Rice",
    in1: "Poultry",
    in2: "Rice",
    in3: "Saffron",
    in4: "Cooking Oil",
    in5: "Parsley",
    in6: "",
    in7: "",
  },
  stuffedcalamari: {
    tier: "Tier 4",
    stat: "30 Constitution",
    lvl: "Lv. 139",
    meal: "Stuffed Calamari",
    in1: "Squid Meat",
    in2: "Rice",
    in3: "Mushroom",
    in4: "Cheese",
    in5: "Tomato",
    in6: "Garlic",
    in7: "",
  },
  grilledwolfloinwithseasonedsquash: {
    tier: "Tier 4",
    stat: "18 Constitution and 12 Strength",
    lvl: "Lv. 136",
    meal: "Grilled Wolf Loin with Seasoned Squash",
    in1: "Tender Wolf Loin",
    in2: "Squash",
    in3: "Butter",
    in4: "Cinnamon",
    in5: "Sugar",
    in6: "Ginger",
    in7: "",
  },
  blueberryglazedhamhockwithsteamedvegetables: {
    tier: "Tier 4",
    stat: "18 Constitution and 12 Dexterity",
    lvl: "Lv. 137",
    meal: "Blueberry Glazed Ham Hock with Steamed Vegetables",
    in1: "Juicy Ham Hock",
    in2: "Blueberry",
    in3: "Honey",
    in4: "Broccoli",
    in5: "Carrot",
    in6: "Cauliflower",
    in7: "",
  },
  turkeyandstuffingwithmushroomgravy: {
    tier: "Tier 4",
    stat: "18 Constitution and 12 Intelligence",
    lvl: "Lv. 138",
    meal: "Turkey and Stuffing with Mushroom Gravy",
    in1: "Poultry Thigh",
    in2: "Butter",
    in3: "Flour",
    in4: "Tarragon",
    in5: "Dill",
    in6: "Berry",
    in7: "Seasoning Blend",
  },
  wolfloinmeatpies: {
    tier: "Tier 4",
    stat: "18 Constitution and 12 Focus",
    lvl: "Lv. 140",
    meal: "Wolf Loin Meat Pies",
    in1: "Tender Wolf Loin",
    in2: "Pastry Crust",
    in3: "Squash",
    in4: "Mushroom",
    in5: "Peppercorn",
    in6: "Oregano",
    in7: "",
  },
  roastedrabbitwithseasonedvegetables: {
    tier: "Tier 5",
    stat: "40 Constitution",
    lvl: "Lv. 189",
    meal: "Roasted Rabbit with Seasoned Vegetables",
    in1: "Sumptuous Rabbit",
    in2: "Butter",
    in3: "Broccoli",
    in4: "Cauliflower",
    in5: "Squash",
    in6: "Tarragon",
    in7: "Oregano",
  },
  turkeythighwithpangravyandspicedwildberries: {
    tier: "Tier 5",
    stat: "24 Constitution and 16 Strength",
    lvl: "Lv. 186",
    meal: "Turkey Thigh with Pan Gravy and Spiced Wild Berries",
    in1: "Poultry Thigh",
    in2: "Butter",
    in3: "Flour",
    in4: "Tarragon",
    in5: "Dill",
    in6: "Berry",
    in7: "Seasoning Blend",
  },
  blackedrayfinnedbarbwithfondantpotatoesandbarley: {
    tier: "Tier 5",
    stat: "24 Constitution and 16 Dexterity",
    lvl: "Lv. 187",
    meal: "Blacked Ray-Finned Barb with Fondant Potatoes and Barley",
    in1: "Ray-Finned Barb",
    in2: "Seasoning Blend",
    in3: "Cooking Oil",
    in4: "Potato",
    in5: "Butter",
    in6: "Thyme",
    in7: "Barley",
  },
  porkbellyfriedrice: {
    tier: "Tier 5",
    stat: "24 Constitution and 16 Intelligence",
    lvl: "Lv. 188",
    meal: "Pork Belly Fried Rice",
    in1: "Pork Belly",
    in2: "Rice",
    in3: "Cooking Oil",
    in4: "Egg",
    in5: "Onion",
    in6: "Garlic",
    in7: "Salt",
  },
  smokedribcapwithcabbageandbarleysoup: {
    tier: "Tier 5",
    stat: "24 Constitution and 16 Focus",
    lvl: "Lv. 190",
    meal: "Smoked Rib Cap with Cabbage and Barley Soup",
    in1: "Prime Red Meat",
    in2: "Paprika",
    in3: "Peppercorn",
    in4: "Cabbage",
    in5: "Barley",
    in6: "Onion",
    in7: "Seasoning Blend",
  },
  blackenedfishfilet: {
    tier: "Tier 2",
    stat: "10 Intelligence",
    lvl: "Lv. 33",
    meal: "Blackened Fish Filet",
    in1: "Ray-Finned Barb",
    in2: "Seasoning Blend",
    in3: "Cooking Oil",
    in4: "Potato",
    in5: "Butter",
    in6: "Thyme",
    in7: "Barley",
  },
  campfirestew: {
    tier: "Tier 2",
    stat: "6 Intelligence and 4 Strength",
    lvl: "Lv. 31",
    meal: "Campfire Stew",
    in1: "Game Meat",
    in2: "Carrot",
    in3: "Onion",
    in4: "Potato",
    in5: "",
    in6: "",
    in7: "",
  },
  garlicrosemarypoultry: {
    tier: "Tier 2",
    stat: "6 Intelligence and 4 Dexterity",
    lvl: "Lv. 32",
    meal: "Garlic Rosemary Poultry",
    in1: "Poultry",
    in2: "Rosemary",
    in3: "Garlic",
    in4: "Cooking Oil",
    in5: "",
    in6: "",
    in7: "",
  },
  fishwithtomatoandbasil: {
    tier: "Tier 2",
    stat: "6 Intelligence and 4 Constitution",
    lvl: "Lv. 34",
    meal: "Fish with Tomato and Basil",
    in1: "Fish Filet",
    in2: "Cooking Oil",
    in3: "Tomato",
    in4: "Basil",
    in5: "",
    in6: "",
    in7: "",
  },
  sausagewithcreamedcorn: {
    tier: "Tier 2",
    stat: "6 Intelligence and 4 Focus",
    lvl: "Lv. 35",
    meal: "Sausage with Creamed Corn",
    in1: "Sausage",
    in2: "Corn",
    in3: "Milk",
    in4: "Salt",
    in5: "",
    in6: "",
    in7: "",
  },
  stuffedporkchop: {
    tier: "Tier 3",
    stat: "20 Intelligence",
    lvl: "Lv.",
    meal: "Stuffed Pork Chop",
    in1: "Pork",
    in2: "Apple",
    in3: "Cabbage",
    in4: "Basil",
    in5: "Thyme",
    in6: "",
    in7: "",
  },
  cornedbeefandcabbage: {
    tier: "Tier 3",
    stat: "12 Intelligence and 8 Strength",
    lvl: "Lv.",
    meal: "Corned Beef and Cabbage",
    in1: "Red Meat",
    in2: "Peppercorn",
    in3: "Cabbage",
    in4: "Onion",
    in5: "Water",
    in6: "",
    in7: "",
  },
  venisonstroganoff: {
    tier: "Tier 3",
    stat: "12 Intelligence and 8 Dexterity",
    lvl: "Lv.",
    meal: "Venison Stroganoff",
    in1: "Venison",
    in2: "Mushroom",
    in3: "Onion",
    in4: "Milk",
    in5: "Parsley",
    in6: "",
    in7: "",
  },
  meatloaf: {
    tier: "Tier 3",
    stat: "12 Intelligence and 8 Constitution",
    lvl: "Lv.",
    meal: "Meatloaf",
    in1: "Venison",
    in2: "Bread",
    in3: "Egg",
    in4: "Tomato",
    in5: "Onion",
    in6: "",
    in7: "",
  },
  fishcakes: {
    tier: "Tier 3",
    stat: "12 Intelligence and 8 Focus",
    lvl: "Lv.",
    meal: "Fish Cakes",
    in1: "Fish Filet",
    in2: "Bread",
    in3: "Onion",
    in4: "Parsley",
    in5: "Cooking Oil",
    in6: "",
    in7: "",
  },
  calamariandtomatostrew: {
    tier: "Tier 4",
    stat: "30 Intelligence",
    lvl: "Lv. 133",
    meal: "Calamari and Tomato Strew",
    in1: "Squid Meat",
    in2: "Garlic",
    in3: "Onion",
    in4: "Parsley",
    in5: "Tomato",
    in6: "Cooking Oil",
    in7: "",
  },
  venisontenderloinwithherbbutter: {
    tier: "Tier 4",
    stat: "18 Intelligence and 12 Strength",
    lvl: "Lv. 131",
    meal: "Venison Tenderloin with Herb Butter",
    in1: "Venison Tenderloin",
    in2: "Peppercorn",
    in3: "Salt",
    in4: "Butter",
    in5: "Garlic",
    in6: "Rosemary",
    in7: "",
  },
  braisedwolfloin: {
    tier: "Tier 4",
    stat: "18 Intelligence and 12 Dexterity",
    lvl: "Lv. 132",
    meal: "Braised Wolf Loin",
    in1: "Tender Wolf Loin",
    in2: "Cooking Oil",
    in3: "Garlic",
    in4: "Cinnamon",
    in5: "Peppercorn",
    in6: "Honey",
    in7: "",
  },
  turkeybreastwithcranberryglaze: {
    tier: "Tier 4",
    stat: "18 Intelligence and 12 Constitution",
    lvl: "Lv. 134",
    meal: "Turkey Breast with Cranberry Glaze",
    in1: "Poultry Breast",
    in2: "Cranberry",
    in3: "Orange",
    in4: "Sage",
    in5: "Rosemary",
    in6: "Thyme",
    in7: "",
  },
  saltedhamwithapplebutter: {
    tier: "Tier 4",
    stat: "18 Intelligence and 12 Focus",
    lvl: "Lv. 135",
    meal: "Salted Ham with Apple Butter",
    in1: "Juicy Ham Hock",
    in2: "Salt",
    in3: "Apple",
    in4: "Butter",
    in5: "Cinnamon",
    in6: "Honey",
    in7: "",
  },
  steamedabaiaserpe: {
    tier: "Tier 5",
    stat: "40 Intelligence",
    lvl: "Lv. 183",
    meal: "Steamed Abaia Serpe",
    in1: "Abaia Serpe",
    in2: "Water",
    in3: "String Bean",
    in4: "Squash",
    in5: "Orange",
    in6: "Butter",
    in7: "Corn",
  },
  squidinkpastawithclams: {
    tier: "Tier 5",
    stat: "24 Intelligence and 16 Strength",
    lvl: "Lv. 181",
    meal: "Squid Ink Pasta with Clams",
    in1: "Pasta",
    in2: "Squid Ink",
    in3: "Clam",
    in4: "Butter",
    in5: "Garlic",
    in6: "Parsley",
    in7: "Sage",
  },
  filetinmushroomsauce: {
    tier: "Tier 5",
    stat: "24 Intelligence and 16 Dexterity",
    lvl: "Lv. 182",
    meal: "Filet in Mushroom Sauce",
    in1: "Prime Red Meat",
    in2: "Mushroom",
    in3: "Butter",
    in4: "Milk",
    in5: "Peppercorn",
    in6: "Parsley",
    in7: "Onion",
  },
  stuffedvenisontenderloin: {
    tier: "Tier 5",
    stat: "24 Intelligence and 16 Focus",
    lvl: "Lv. 185",
    meal: "Stuffed Venison Tenderloin",
    in1: "Venison Tenderloin",
    in2: "Onion",
    in3: "Rice",
    in4: "Saffron",
    in5: "Mushroom",
    in6: "Sage",
    in7: "Thyme",
  },
  glazedbearwithsauteedvegetables: {
    tier: "Tier 5",
    stat: "24 Intelligence and 16 Constitution",
    lvl: "Lv. 184",
    meal: "Glazed Bear with Sauteed Vegetables",
    in1: "Rich Bear Flank",
    in2: "Honey",
    in3: "String Bean",
    in4: "Mushroom",
    in5: "Cauliflower",
    in6: "Onion",
    in7: "Cooking Oil",
  },
  meloninfusion: {
    tier: "Tier 3",
    stat: "10 Jewelcrafting",
    lvl: "Lv. 52",
    meal: "Melon Infusion",
    in1: "Melon",
    in2: "Water",
    in3: "Honey",
    in4: "Cinnamon",
    in5: "Nutmeg",
    in6: "",
    in7: "",
  },
  sweetfruittrifle: {
    tier: "Tier 4",
    stat: "12 Jewelcrafting",
    lvl: "Lv. 102",
    meal: "Sweet Fruit Trifle",
    in1: "Melon",
    in2: "Berry",
    in3: "Nut",
    in4: "Honey",
    in5: "Blueberry",
    in6: "Cinnamon",
    in7: "",
  },
  glazedmelonbread: {
    tier: "Tier 5",
    stat: "15 Jewelcrafting",
    lvl: "Lv. 152",
    meal: "Glazed Melon Bread",
    in1: "Melon",
    in2: "Corn",
    in3: "Honey",
    in4: "Sugar",
    in5: "Mint",
    in6: "Cooking Oil",
    in7: "Ginger",
  },
  honeybrew: {
    tier: "Tier 3",
    stat: "10 Armoring",
    lvl: "Lv. 55",
    meal: "Honey Brew",
    in1: "Barley",
    in2: "Water",
    in3: "Honey",
    in4: "Ginger",
    in5: "Nutmeg",
    in6: "",
    in7: "",
  },
  stronghoneybrew: {
    tier: "Tier 4",
    stat: "12 Armoring",
    lvl: "Lv. 105",
    meal: "Strong Honey Brew",
    in1: "Barley",
    in2: "Wheat",
    in3: "Honey",
    in4: "Nut",
    in5: "Ginger",
    in6: "Butter",
    in7: "",
  },
  spicycabbagesoup: {
    tier: "Tier 5",
    stat: "15 Armoring",
    lvl: "Lv. 155",
    meal: "Spicy Cabbage Soup",
    in1: "Barley",
    in2: "Cabbage",
    in3: "Water",
    in4: "Peppercorn",
    in5: "Carrot",
    in6: "Cauliflower",
    in7: "String Bean",
  },
  wildberrycompote: {
    tier: "Tier 3",
    stat: "10 Arcana",
    lvl: "Lv. 54",
    meal: "Wild Berry Compote",
    in1: "Berry",
    in2: "Honey",
    in3: "Water",
    in4: "Strawberry",
    in5: "Mint",
    in6: "",
    in7: "",
  },
  berrybrew: {
    tier: "Tier 4",
    stat: "12 Arcana",
    lvl: "Lv. 104",
    meal: "Berry Brew",
    in1: "Berry",
    in2: "Strawberry",
    in3: "Water",
    in4: "Honey",
    in5: "Orange",
    in6: "Blueberry",
    in7: "",
  },
  sweetwildberryinfusion: {
    tier: "Tier 5",
    stat: "15 Arcana",
    lvl: "Lv. 154",
    meal: "Sweet Wild Berry Infusion",
    in1: "Berry",
    in2: "Melon",
    in3: "Water",
    in4: "Sugar",
    in5: "Tarragon",
    in6: "Strawberry",
    in7: "Blueberry",
  },
  herbcrustedbroccoli: {
    tier: "Tier 3",
    stat: "10 Weaponsmithing",
    lvl: "Lv. 51",
    meal: "Herb-Crusted Broccoli",
    in1: "Broccoli",
    in2: "Seasoning Blend",
    in3: "Nut",
    in4: "Cheese",
    in5: "Milk",
    in6: "",
    in7: "",
  },
  roastedvegetablemedley: {
    tier: "Tier 4",
    stat: "12 Weaponsmithing",
    lvl: "Lv. 101",
    meal: "Roasted Vegetable Medley",
    in1: "Broccoli",
    in2: "Squash",
    in3: "Honey",
    in4: "Seasoning Blend",
    in5: "Cauliflower",
    in6: "Cooking Oil",
    in7: "",
  },
  savoryvegetablemedley: {
    tier: "Tier 5",
    stat: "15 Weaponsmithing",
    lvl: "Lv. 151",
    meal: "Savory Vegetable Medley",
    in1: "Broccoli",
    in2: "Carrot",
    in3: "Seasoning Blend",
    in4: "Oregano",
    in5: "Cooking Oil",
    in6: "String Bean",
    in7: "Cauliflower",
  },
  herbroastedsquash: {
    tier: "Tier 3",
    stat: "10 Engineering",
    lvl: "Lv. 53",
    meal: "Herb-Roasted Squash",
    in1: "Squash",
    in2: "Nut",
    in3: "Honey",
    in4: "Ginger",
    in5: "Butter",
    in6: "",
    in7: "",
  },
  creamedcorn: {
    tier: "Tier 4",
    stat: "12 Engineering",
    lvl: "Lv. 103",
    meal: "Creamed Corn",
    in1: "Squash",
    in2: "Corn",
    in3: "Water",
    in4: "Seasoning Blend",
    in5: "Tomato",
    in6: "Basil",
    in7: "",
  },
  herbcrustedvegetables: {
    tier: "Tier 5",
    stat: "15 Engineering",
    lvl: "Lv. 153",
    meal: "Herb-Crusted Vegetables",
    in1: "Squash",
    in2: "Cabbage",
    in3: "Seasoning Blend",
    in4: "Garlic",
    in5: "Rosemary",
    in6: "Cooking Oil",
    in7: "String Bean",
  },
  cookedcorn: {
    tier: "Tier 1",
    stat: "1000 Harvesting",
    lvl: "Lv. 8",
    meal: "Cooked Corn",
    in1: "Corn",
    in2: "Butter",
    in3: "Salt",
    in4: "",
    in5: "",
    in6: "",
    in7: "",
  },
  cornbread: {
    tier: "Tier 2",
    stat: "1400 Harvesting",
    lvl: "Lv. 18",
    meal: "Cornbread",
    in1: "Corn",
    in2: "Seasoning Blend",
    in3: "Cauliflower",
    in4: "Salt",
    in5: "",
    in6: "",
    in7: "",
  },
  herbcrustedcornonthecob: {
    tier: "Tier 3",
    stat: "1700 Harvesting",
    lvl: "Lv. 57",
    meal: "Herb-Crusted Corn on the Cob",
    in1: "Corn",
    in2: "Seasoning Blend",
    in3: "Nut",
    in4: "Milk",
    in5: "Cheese",
    in6: "",
    in7: "",
  },
  breakfastbread: {
    tier: "Tier 4",
    stat: "1900 Harvesting",
    lvl: "Lv. 107",
    meal: "Breakfast Bread",
    in1: "Corn",
    in2: "Egg",
    in3: "Honey",
    in4: "Nut",
    in5: "Seasoning Blend",
    in6: "Tomato",
    in7: "",
  },
  spicysteakpie: {
    tier: "Tier 5",
    stat: "2000 Harvesting",
    lvl: "Lv. 157",
    meal: "Spicy Steak Pie",
    in1: "Corn",
    in2: "Red Meat",
    in3: "Seasoning Blend",
    in4: "Peppercorn",
    in5: "Butter",
    in6: "Carrot",
    in7: "String Bean",
  },
  roastedcarrots: {
    tier: "Tier 1",
    stat: "1000 Skinning",
    lvl: "Lv. 9",
    meal: "Roasted Carrots",
    in1: "Carrot",
    in2: "Honey",
    in3: "Nutmeg",
    in4: "",
    in5: "",
    in6: "",
    in7: "",
  },
  herbroastedcarrots: {
    tier: "Tier 2",
    stat: "1400 Skinning",
    lvl: "Lv. 19",
    meal: "Herb-Roasted Carrots",
    in1: "Carrot",
    in2: "Water",
    in3: "Garlic",
    in4: "Peppercorn",
    in5: "",
    in6: "",
    in7: "",
  },
  carrotsoup: {
    tier: "Tier 3",
    stat: "1700 Skinning",
    lvl: "Lv.",
    meal: "Carrot Soup",
    in1: "Carrot",
    in2: "Water",
    in3: "Seasoning Blend",
    in4: "Cooking Oil",
    in5: "Paprika",
    in6: "",
    in7: "",
  },
  vegetableboil: {
    tier: "Tier 4",
    stat: "1900 Skinning",
    lvl: "Lv. 108",
    meal: "Vegetable Boil",
    in1: "Carrot",
    in2: "Cabbage",
    in3: "Water",
    in4: "Nut",
    in5: "Cauliflower",
    in6: "Cooking Oil",
    in7: "",
  },
  savoryfishcake: {
    tier: "Tier 5",
    stat: "2000 Skinning",
    lvl: "Lv. 158",
    meal: "Savory Fish Cake",
    in1: "Carrot",
    in2: "Fish Filet",
    in3: "Seasoning Blend",
    in4: "Garlic",
    in5: "String Bean",
    in6: "Butter",
    in7: "Rosemary",
  },
  roastedpotatoes: {
    tier: "Tier 1",
    stat: "1000 Minning",
    lvl: "Lv. 7",
    meal: "Roasted Potatoes",
    in1: "Potato",
    in2: "Butter",
    in3: "Peppercorn",
    in4: "",
    in5: "",
    in6: "",
    in7: "",
  },
  herbroastedpotatoes: {
    tier: "Tier 2",
    stat: "1400 Minning",
    lvl: "Lv. 17",
    meal: "Herb-Roasted Potatoes",
    in1: "Potato",
    in2: "Honey",
    in3: "Butter",
    in4: "Cinnamon",
    in5: "",
    in6: "",
    in7: "",
  },
  boiledpotatoes: {
    tier: "Tier 3",
    stat: "1700 Minning",
    lvl: "Lv. 56",
    meal: "Boiled Potatoes",
    in1: "Potato",
    in2: "Water",
    in3: "Seasoning Blend",
    in4: "Butter",
    in5: "Cauliflower",
    in6: "",
    in7: "",
  },
  poultrywithroastedpotatoes: {
    tier: "Tier 4",
    stat: "1900 Minning",
    lvl: "Lv. 106",
    meal: "Poultry with Roasted Potatoes",
    in1: "Potato",
    in2: "Poultry",
    in3: "Seasoning Blend",
    in4: "Nut",
    in5: "Sausage",
    in6: "Butter",
    in7: "",
  },
  saltedroastedvegetables: {
    tier: "Tier 5",
    stat: "2000 Minning",
    lvl: "Lv. 156",
    meal: "Salted Roasted Vegetables",
    in1: "Potato",
    in2: "Squash",
    in3: "Nut",
    in4: "Salt",
    in5: "Butter",
    in6: "Parsley",
    in7: "Oregano",
  },
  roastedcabbage: {
    tier: "Tier 1",
    stat: "1000 Logging",
    lvl: "Lv. 10",
    meal: "Roasted Cabbage",
    in1: "Cabbage",
    in2: "Cooking Oil",
    in3: "Dill",
    in4: "",
    in5: "",
    in6: "",
    in7: "",
  },
  boiledcabbage: {
    tier: "Tier 2",
    stat: "1400 Logging",
    lvl: "Lv. 20",
    meal: "Boiled Cabbage",
    in1: "Cabbage",
    in2: "Nut",
    in3: "Cooking Oil",
    in4: "Saffron",
    in5: "",
    in6: "",
    in7: "",
  },
  herbroastedcabbage: {
    tier: "Tier 3",
    stat: "1700 Logging",
    lvl: "Lv.",
    meal: "Herb-Roasted Cabbage",
    in1: "Cabbage",
    in2: "Nut",
    in3: "Seasoning Blend",
    in4: "Butter",
    in5: "Cauliflower",
    in6: "",
    in7: "",
  },
  cabbagewrappedroastedfish: {
    tier: "Tier 4",
    stat: "1900 Logging",
    lvl: "Lv. 109",
    meal: "Cabbage-Wrapped Roasted Fish",
    in1: "Cabbage",
    in2: "Fish Filet",
    in3: "Water",
    in4: "Seasoning Blend",
    in5: "Cooking Oil",
    in6: "Cauliflower",
    in7: "",
  },
  saltedpoultrywithcabbage: {
    tier: "Tier 5",
    stat: "2000 Logging",
    lvl: "Lv. 159",
    meal: "Salted Poultry with Cabbage",
    in1: "Cabbage",
    in2: "Poultry",
    in3: "Nut",
    in4: "Peppercorn",
    in5: "Butter",
    in6: "String Bean",
    in7: "Seasoning Blend",
  },
};
